trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

name: $(Date:yyyy).$(Date:MM).$(Date:dd).$(Rev:rr)

steps:
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec:

  - task: PowerShell@2
    displayName: 'Powershell Build Script'
    inputs:
      targetType: filePath
      filePath: 'Build\build.ps1'
    env:
      PROJECT_PUBKEY: $(Project.PubKey)
      PROJECT_PUBUSER: $(Project.PubUser)
  
  - task: PublishTestResults@2
    displayName: 'Publish Test Results/TestResults_PS*.xml'
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: 'Build/TestResults_PS*.xml'
    condition: succeededOrFailed()
  
  - task: reportgenerator@4
    displayName: 'Report Generator/CodeCoverage_PS*.xml'
    inputs:
      reports: 'Build/CodeCoverage_PS*.xml'
      reporttypes: 'HtmlInline_AzurePipelines'
      sourcedirs: .
    condition: not(contains(variables['BHCommitMessage'],'!skipcodecoverage'))
  
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage from Build/CodeCoverage_PS*.xml'
    inputs:
      summaryFileLocation: 'Build/CodeCoverage_PS*.xml'
      reportDirectory: coveragereport
    condition: not(contains(variables['BHCommitMessage'],'!skipcodecoverage'))
  
  - task: ArchiveFiles@2
    displayName: 'ZIP build directory'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      replaceExistingArchive: true
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'zip'
      publishLocation: 'Container'
  
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.SourcesDirectory)\BuildOutput\*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '/8e899429-2204-41f0-820a-3b7b5cb96ddd'
      verbosityPush: 'Detailed'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
